# CI config for flutter.

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  web:
    name: build & test the Flutter web version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2.0.4
        with:
          channel: "stable"
          flutter-version: "3.0.0"
      - run: flutter pub get
      # - run: flutter test
      - run: flutter build web
